# Generated by Django 4.1.3 on 2024-01-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatBiteBistroapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='BeatBiteBistroapi.OrderItem', to='BeatBiteBistroapi.item'),
        ),
    ]
