# Generated by Django 4.1.3 on 2024-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatBiteBistroapi', '0003_alter_customer_phone_number_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
